server:
  port: 8080

spring:
  application:
    name: basic-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/basic-api
    username: root
    password: root

jwt:
  secret: secret

